cargo-features = ["edition2024"]
[package]
name = "fundraiser"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
pinocchio = "0.9.2"
pinocchio-pubkey = "0.3.0"
pinocchio-token = "0.4.0"
