[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
silicon = "8TjYjuCkF7NCCcWCjFsFfrdysDXUsLXXAfK37unQJJE3"
vault = "2ypHbf9ZVBhaM9LB8i1QaDws7jBNXHGhqKLWugktgUxm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
